language: python

sudo: required

branches:
    only:
        - master

services:
    - docker

install:
    - docker pull jvarho/pylibscrypt

script:
    - docker run -v ${PWD}:/app jvarho/pylibscrypt
